version: '3.8'

services:
  apache:
    build: ./apache
    ports:
      - "80:80"
    volumes:
      - ./apache/www:/var/www/html
    depends_on:
      - mysql
    networks:
      - lampnet
      - monitoring_net

  mysql:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: kali
      MYSQL_DATABASE: Inventario
      MYSQL_USER: kali
      MYSQL_PASSWORD: kali
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - lampnet
      - monitoring_net

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - "8080:80"
    environment:
      PMA_HOST: mysql
      MYSQL_ROOT_PASSWORD: kali
    depends_on:
      - mysql
    networks:
      - lampnet
      - monitoring_net

  node_exporter:
    image: prom/node-exporter:latest
    container_name: node_exporter
    networks:
      - monitoring_net
    restart: unless-stopped

volumes:
  mysql_data:

networks:
  lampnet:
    driver: bridge
  monitoring_net:
    external: true

